version: "3.8"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: .env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    privileged: true
    volumes:
      - db:/data/db
    networks:
      - my_network
  r-backend:
    build: ./openeocubes
    container_name: r-backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - TZ=Etc/UTC
      - DEBIAN_FRONTEND=noninteractive
      - AWSHOST=r-backend
    networks:
      - my_network
  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - OPENEOCUBES_URI=http://r-backend:8000
    stdin_open: true
    tty: true
    networks:
      - my_network

volumes:
  db:

networks:
  my_network:
    driver: bridge