version: "3.8"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: .env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    privileged: true
    volumes:
      - db:/data/db
  r-backend:
    build: ./openeocubes
    container_name: openeocubes
    ports:
      - "8000:8000"
    restart: always
    environment:
      - TZ=Etc/UTC
      - DEBIAN_FRONTEND=noninteractive
  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db:
